################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CMakeFiles/3.16.3/CompilerIdC \
CMakeFiles/CheckTypeSize \
build/app_trace \
build/app_trace/gcov \
build/app_update \
build/bootloader \
build/bootloader/bootloader_support/src \
build/bootloader/log \
build/bootloader/main \
build/bootloader/micro-ecc/micro-ecc \
build/bootloader/soc/esp32 \
build/bootloader/spi_flash \
build/bootloader_support/src \
build/bt \
build/coap/libcoap/src \
build/coap/port \
build/console/argtable3 \
build/console \
build/console/linenoise \
build/cxx \
build/driver \
build/esp32 \
build/esp32/hwcrypto \
build/esp_adc_cal \
build/ethernet \
build/ethernet/eth_phy \
build/expat/library \
build/expat/port \
build/fatfs/src \
build/freertos \
build/heap \
build/jsmn/src \
build/json/library \
build/json/port \
build/libsodium/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_auth \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/libsodium/libsodium/src/libsodium/crypto_box \
build/libsodium/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_core/hchacha20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/libsodium/libsodium/src/libsodium/crypto_core/salsa/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash \
build/libsodium/libsodium/src/libsodium/crypto_hash \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256 \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512 \
build/libsodium/libsodium/src/libsodium/crypto_kdf/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_kdf \
build/libsodium/libsodium/src/libsodium/crypto_kx \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/libsodium/libsodium/src/libsodium/crypto_secretbox \
build/libsodium/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_shorthash \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/libsodium/libsodium/src/libsodium/crypto_sign \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20 \
build/libsodium/libsodium/src/libsodium/crypto_stream \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_verify/sodium \
build/libsodium/libsodium/src/libsodium/randombytes \
build/libsodium/libsodium/src/libsodium/sodium \
build/libsodium/port/crypto_hash_mbedtls \
build/libsodium/port \
build/log \
build \
build/lwip/api \
build/lwip/apps \
build/lwip/apps/ping \
build/lwip/apps/sntp \
build/lwip/core \
build/lwip/core/ipv4 \
build/lwip/core/ipv6 \
build/lwip/netif \
build/lwip/port/debug \
build/lwip/port/freertos \
build/lwip/port/netif \
build/lwip/port \
build/main \
build/mbedtls/library \
build/mbedtls/port \
build/mdns \
build/micro-ecc/micro-ecc \
build/newlib \
build/nghttp/nghttp2/lib \
build/nghttp/port \
build/nvs_flash/src \
build/openssl/library \
build/openssl/platform \
build/pthread \
build/sdmmc \
build/soc/esp32 \
build/spi_flash \
build/spiffs \
build/spiffs/spiffs/src \
build/tcpip_adapter \
build/ulp \
build/vfs \
build/wear_levelling \
build/wpa_supplicant/port \
build/wpa_supplicant/src/crypto \
build/wpa_supplicant/src/fast_crypto \
build/xtensa-debug-module \
build2/bootloader \
build2 \
main \
test \

